version: 2.1
orbs:
  docker: circleci/docker@0.5.19
workflows:
  version: 2
  build-and-publish:
    jobs:
      - docker/publish:
          cache_from: "pennlabs/shibboleth-sp-nginx:latest"
          image: pennlabs/shibboleth-sp-nginx
          tag: "${CIRCLE_TAG},latest"
          context: docker-publish
          filters:
            tags:
              only: /^[0-9.]+/
            branches:
              ignore: /.*/
